from rest_framework import serializers


def _text(**kwargs):
    return serializers.CharField(required=False, allow_null=True, allow_blank=True, **kwargs)


def _int(**kwargs):
    return serializers.IntegerField(required=False, allow_null=True, **kwargs)


def _bool(**kwargs):
    return serializers.BooleanField(required=False, allow_null=True, **kwargs)


class AgrohubSurveySerializer(serializers.Serializer):
    type = serializers.ChoiceField(choices=["agrohub"])
    email = _text()
    nombre_aplicador = _text()
    fecha_aplicacion = serializers.DateField(required=False, allow_null=True)
    municipio = _text()
    vereda = _text()
    nombre_organizacion = _text()
    tipo_organizacion = _text()
    anio_conformacion = _int()
    numero_miembros = _int()
    numero_nucleos_familiares = _int()
    cobertura_territorial = _text()
    representante_legal = _text()
    contacto = _text()
    tipos_agricultura = _text()
    cultivan_hortalizas = _text()
    cuales_hortalizas = _text()
    area_hortalizas = _int()
    destino_hortalizas = _text()
    actividades_complementarias = _text()
    tiene_patio = _text()
    area_patio = _int()
    condiciones_terreno = _text()
    formalizacion = _text()
    asociatividad = _text()
    experiencia_proyectos = _text()
    descripcion_experiencia = _text()
    tiene_estatutos_plan = _text()
    acceso_mercado = _text()
    frecuencia_venta = _text()
    manejo_administrativo = _text()
    tecnologias_usadas = _text()
    otras_tecnologias = _text()
    capacidad_aprendizaje = _text()
    comentarios = _text()
    conectividad = _text()
    expectativas = _text()
    compromisos = _text()
    limitaciones = _text()
    latitud = _text()
    longitud = _text()


class EducativaSurveySerializer(serializers.Serializer):
    type = serializers.ChoiceField(choices=["educativa"])
    email = _text()
    nombre_aplicador = _text()
    fecha_aplicacion = serializers.DateField(required=False, allow_null=True)
    municipio = _text()
    vereda = _text()
    nombre_institucion = _text()
    codigo_dane = _text()
    nombre_directivo = _text()
    contacto = _text()
    tipo_institucion = _text()
    sedes = _text()
    numero_estudiantes = _int()
    numero_docentes = _int()
    grados_atiende = _text()
    tiene_prae = _bool()
    prae_descripcion = _text()
    experiencia_proyectos = _bool()
    descripcion_proyectos = _text()
    tiene_huerta = _bool()
    area_huerta = _int()
    uso_huerta = _text()
    temas_agroambientales = _text()
    espacio_agrohub = _bool()
    area_agrohub = _int()
    condiciones_terreno = _text()
    internet = _text()
    espacios_complementarios = _bool()
    cantidad_espacios = _int()
    laboratorio = _bool()
    laboratorio_funciona = _bool()
    actores_comunitarios = _text()
    tiene_alianzas = _bool()
    descripcion_alianzas = _text()
    tiene_semilleros = _bool()
    nombre_grupo = _text()
    interes_agricultura = _text()
    medios_comunicacion = _text()
    expectativas = _text()
    compromisos = _text()
    limitaciones = _text()
    comentarios = _text()
    anexa_documentos = _bool()
    latitud = _text()
    longitud = _text()


class DerechoHumanoAlimentarioSurveySerializer(serializers.Serializer):
    type = serializers.ChoiceField(choices=["derecho_humano_alimentario"])
    email = _text()
    fecha_aplicacion = serializers.DateField(required=False, allow_null=True)
    nombre_jefe_hogar = _text()
    edad = _int()
    genero = _text()
    departamento = _text()
    municipio = _text()
    subregion = _text()
    numero_miembros_hogar = _int()
    nivel_educativo = _text()
    nombre_encuestador = _text()
    cargo_encuestador = _text()
    dedicado_agricultura = _bool()
    cultivos_principales = _text()
    razon_produccion = _text()
    cobertura_necesidades = _bool()
    meses_escasez = _text()
    cambios_produccion = _text()
    razon_cambios = _text()
    acceso_insumos_agricolas = _bool()
    asistencia_tecnica = _bool()
    compra_suficiente_alimentos = _bool()
    acceso_mercado = _bool()
    distancia_mercado = _text()
    alimento_asequible = _bool()
    reduccion_consumo = _bool()
    ayuda_alimentaria = _bool()
    dieta_balanceada = _bool()
    consumo_grupos_alimenticios = _text()
    agua_potable_preparacion = _bool()
    enfermedades_transmitidas = _bool()
    alimentos_culturalmente_aceptables = _bool()
    higiene_manipulacion = _bool()
    conoce_derecho_alimentacion = _bool()
    cree_derecho_respetado = _bool()
    medidas_mejorar_acceso = _text()
    latitud = _text()
    longitud = _text()


SERIALIZER_BY_TYPE = {
    "agrohub": AgrohubSurveySerializer,
    "educativa": EducativaSurveySerializer,
    "derecho_humano_alimentario": DerechoHumanoAlimentarioSurveySerializer,
}


class SurveyListRequestSerializer(serializers.Serializer):
    email = serializers.CharField()
    surveys = serializers.ListField(child=serializers.DictField(), allow_empty=False)
