# Generated by Django 5.0.14 on 2026-08-03 02:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EncuestaNutricional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_encuesta', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('nombre_encuestador', models.CharField(max_length=255)),
                ('cedula_encuestador', models.CharField(max_length=50)),
                ('fecha_aplicacion', models.DateField()),
                ('codigo_cuestionario', models.CharField(blank=True, max_length=100, null=True)),
                ('municipio', models.CharField(max_length=100)),
                ('vereda_comunidad', models.CharField(max_length=255)),
                ('num_personas_hogar', models.IntegerField(blank=True, null=True)),
                ('num_mujeres_hogar', models.IntegerField(blank=True, null=True)),
                ('hay_menores_18', models.BooleanField(blank=True, null=True)),
                ('num_ninos_menores_5', models.IntegerField(blank=True, null=True)),
                ('fuente_ingreso_principal', models.CharField(blank=True, max_length=100, null=True)),
                ('tiene_huerta_o_animales', models.BooleanField(blank=True, null=True)),
                ('jefatura_hogar', models.CharField(blank=True, max_length=50, null=True)),
                ('estabilidad_ingreso', models.CharField(blank=True, max_length=100, null=True)),
                ('dias_cereales_tuberculos', models.IntegerField(blank=True, null=True)),
                ('dias_leguminosas', models.IntegerField(blank=True, null=True)),
                ('dias_carnes_pescado_huevo', models.IntegerField(blank=True, null=True)),
                ('dias_lacteos', models.IntegerField(blank=True, null=True)),
                ('dias_frutas', models.IntegerField(blank=True, null=True)),
                ('dias_verduras', models.IntegerField(blank=True, null=True)),
                ('dias_grasas', models.IntegerField(blank=True, null=True)),
                ('dias_azucares_ultraprocesados', models.IntegerField(blank=True, null=True)),
                ('puntaje_diversidad_dietetica', models.IntegerField(blank=True, null=True)),
                ('frecuencia_frutas_semana', models.CharField(blank=True, max_length=30, null=True)),
                ('frecuencia_verduras_semana', models.CharField(blank=True, max_length=30, null=True)),
                ('frecuencia_bebidas_azucaradas', models.CharField(blank=True, max_length=30, null=True)),
                ('comidas_por_dia', models.CharField(blank=True, max_length=20, null=True)),
                ('frecuencia_comida_fuera_hogar', models.CharField(blank=True, max_length=30, null=True)),
                ('proporcion_autoconsumo', models.CharField(blank=True, max_length=30, null=True)),
                ('alimentos_preferidos', models.JSONField(blank=True, null=True)),
                ('preocupacion_alimentos_acabaran', models.BooleanField(blank=True, null=True)),
                ('alimentos_se_acabaron', models.BooleanField(blank=True, null=True)),
                ('adulto_omitio_comida_principal', models.BooleanField(blank=True, null=True)),
                ('sintio_hambre_sin_comer', models.BooleanField(blank=True, null=True)),
                ('puntaje_inseguridad_alimentaria', models.IntegerField(blank=True, null=True)),
                ('clasificacion_seguridad_alimentaria', models.CharField(blank=True, max_length=60, null=True)),
                ('consentimiento_informado', models.BooleanField()),
                ('observaciones_encuestador', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'encuestas_nutricionales',
            },
        ),
        migrations.CreateModel(
            name='PersonaNutricional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('edad_anios', models.IntegerField(blank=True, null=True)),
                ('sexo', models.CharField(blank=True, max_length=20, null=True)),
                ('area_residencia', models.CharField(blank=True, max_length=20, null=True)),
                ('nivel_educativo', models.CharField(blank=True, max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'personas_nutricionales',
            },
        ),
        migrations.CreateModel(
            name='Miembro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percepcion_estado_nutricional', models.CharField(blank=True, max_length=20, null=True)),
                ('cambio_peso_no_intencional', models.BooleanField(blank=True, null=True)),
                ('nino_en_control_crecimiento', models.CharField(blank=True, max_length=10, null=True)),
                ('peso_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('talla_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('circunferencia_cintura_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('perimetro_brazo_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('grupo_perimetro_brazo', models.CharField(blank=True, max_length=30, null=True)),
                ('imc_calculado', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('encuesta', models.ForeignKey(db_column='encuesta_id', on_delete=django.db.models.deletion.CASCADE, related_name='miembros', to='encuesta_nutricional.encuestanutricional')),
                ('persona', models.ForeignKey(db_column='persona_id', on_delete=django.db.models.deletion.CASCADE, related_name='miembros', to='encuesta_nutricional.personanutricional')),
            ],
            options={
                'db_table': 'encuesta_nutricional_miembros',
            },
        ),
    ]
