# Generated by Django 5.0.14 on 2026-09-04 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tema', models.CharField(max_length=255)),
                ('responsable', models.CharField(blank=True, max_length=255, null=True)),
                ('lugar', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('hora_inicio', models.TimeField(blank=True, null=True)),
                ('hora_final', models.TimeField(blank=True, null=True)),
                ('documento_escaneado', models.TextField(blank=True, null=True)),
                ('texto_crudo_ocr', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'eventos_asistencia',
            },
        ),
        migrations.CreateModel(
            name='PersonaAsistente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(blank=True, max_length=20, null=True)),
                ('numero_documento', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('genero', models.CharField(blank=True, max_length=1, null=True)),
                ('pertenencia_etnica', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'personas_asistentes',
            },
        ),
        migrations.CreateModel(
            name='RegistroAsistencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('municipio', models.CharField(blank=True, max_length=100, null=True)),
                ('telefono', models.CharField(blank=True, max_length=50, null=True)),
                ('edad', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('evento', models.ForeignKey(db_column='evento_id', on_delete=django.db.models.deletion.CASCADE, related_name='asistentes', to='asistencia_eventos.evento')),
                ('persona', models.ForeignKey(db_column='persona_id', on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='asistencia_eventos.personaasistente')),
            ],
            options={
                'db_table': 'registros_asistencia',
                'unique_together': {('evento', 'persona')},
            },
        ),
    ]
