# Generated by Django 5.0.14 on 2026-09-23 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia_eventos', '0001_initial'),
        ('user_activity', '0003_remove_user_auth_token_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='registrado_por',
            field=models.ForeignKey(blank=True, db_column='registrado_por_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_asistencia_registrados', to='user_activity.user'),
        ),
    ]
