# Generated by Django 5.0.14 on 2026-09-23 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia_eventos', '0002_evento_registrado_por'),
        ('user_activity', '0003_remove_user_auth_token_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='editado_por',
            field=models.ForeignKey(blank=True, db_column='editado_por_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_asistencia_editados', to='user_activity.user'),
        ),
        migrations.AddField(
            model_name='evento',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
