# Generated by Django 5.0.14 on 2026-10-08 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_activity', '0003_remove_user_auth_token_session'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgroHub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=50, unique=True)),
                ('familias', models.JSONField(default=list)),
                ('departamento', models.CharField(max_length=100)),
                ('municipio', models.CharField(max_length=100)),
                ('es_cabecera_municipal', models.BooleanField()),
                ('vereda', models.CharField(blank=True, max_length=150, null=True)),
                ('asociaciones', models.JSONField(default=list)),
                ('grupo_etnico', models.CharField(blank=True, max_length=20, null=True)),
                ('comunidad', models.CharField(blank=True, max_length=100, null=True)),
                ('cultivos', models.JSONField(default=list)),
                ('latitud', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitud', models.DecimalField(decimal_places=6, max_digits=9)),
                ('video', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(blank=True, db_column='creado_por_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='user_activity.user')),
                ('editado_por', models.ForeignKey(blank=True, db_column='editado_por_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='user_activity.user')),
            ],
            options={
                'db_table': 'agrohubs',
                'ordering': ['numero'],
            },
        ),
    ]
