# Generated by Django 5.0.14 on 2026-09-08 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dispositivo',
            fields=[
                ('device_id', models.CharField(db_column='device_id', max_length=64, primary_key=True, serialize=False)),
                ('base_topic', models.CharField(db_column='base_topic', max_length=128)),
                ('client_id', models.CharField(blank=True, db_column='client_id', max_length=64, null=True, unique=True)),
                ('nombre', models.CharField(blank=True, db_column='nombre', max_length=255, null=True)),
                ('activo', models.BooleanField(db_column='activo', default=True)),
                ('primera_vez_visto', models.DateTimeField(db_column='primera_vez_visto')),
                ('ultima_vez_visto', models.DateTimeField(blank=True, db_column='ultima_vez_visto', null=True)),
                ('creado_en', models.DateTimeField(db_column='creado_en')),
            ],
            options={
                'db_table': 'dispositivos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EstadoConexion',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('device_id', models.CharField(db_column='device_id', max_length=64)),
                ('estado', models.CharField(db_column='estado', max_length=16)),
                ('recibido_en', models.DateTimeField(db_column='recibido_en')),
            ],
            options={
                'db_table': 'estados_conexion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EstadoValvula',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('device_id', models.CharField(db_column='device_id', max_length=64)),
                ('medido_en', models.DateTimeField(db_column='medido_en')),
                ('ro1', models.CharField(blank=True, db_column='ro1', max_length=32, null=True)),
                ('ro2', models.CharField(blank=True, db_column='ro2', max_length=32, null=True)),
                ('origen', models.CharField(db_column='origen', max_length=32)),
                ('ultimo_comando', models.CharField(blank=True, db_column='ultimo_comando', max_length=64, null=True)),
                ('recibido_en', models.DateTimeField(db_column='recibido_en')),
                ('payload_crudo', models.JSONField(db_column='payload_crudo')),
            ],
            options={
                'db_table': 'estados_valvula',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Healthcheck',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('device_id', models.CharField(db_column='device_id', max_length=64)),
                ('medido_en', models.DateTimeField(db_column='medido_en')),
                ('mqtt_conectado', models.BooleanField(blank=True, db_column='mqtt_conectado', null=True)),
                ('ultimo_uplink', models.DateTimeField(blank=True, db_column='ultimo_uplink', null=True)),
                ('modo_control', models.CharField(blank=True, db_column='modo_control', max_length=16, null=True)),
                ('override_manual', models.BooleanField(blank=True, db_column='override_manual', null=True)),
                ('valvulas', models.JSONField(blank=True, db_column='valvulas', null=True)),
                ('recibido_en', models.DateTimeField(db_column='recibido_en')),
                ('payload_crudo', models.JSONField(db_column='payload_crudo')),
            ],
            options={
                'db_table': 'healthchecks',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LecturaAmbiente',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('device_id', models.CharField(db_column='device_id', max_length=64)),
                ('dev_eui', models.CharField(blank=True, db_column='dev_eui', max_length=64, null=True)),
                ('medido_en', models.DateTimeField(db_column='medido_en')),
                ('temperatura', models.FloatField(blank=True, db_column='temperatura', null=True)),
                ('humedad', models.FloatField(blank=True, db_column='humedad', null=True)),
                ('recuperado', models.BooleanField(db_column='recuperado', default=False)),
                ('guardado_en', models.DateTimeField(blank=True, db_column='guardado_en', null=True)),
                ('reenviado_en', models.DateTimeField(blank=True, db_column='reenviado_en', null=True)),
                ('recibido_en', models.DateTimeField(db_column='recibido_en')),
                ('payload_crudo', models.JSONField(db_column='payload_crudo')),
            ],
            options={
                'db_table': 'lecturas_ambiente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LecturaSuelo',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('device_id', models.CharField(db_column='device_id', max_length=64)),
                ('dev_eui', models.CharField(blank=True, db_column='dev_eui', max_length=64, null=True)),
                ('medido_en', models.DateTimeField(db_column='medido_en')),
                ('humedad_suelo', models.FloatField(blank=True, db_column='humedad_suelo', null=True)),
                ('temperatura_suelo', models.FloatField(blank=True, db_column='temperatura_suelo', null=True)),
                ('conductividad', models.FloatField(blank=True, db_column='conductividad', null=True)),
                ('recuperado', models.BooleanField(db_column='recuperado', default=False)),
                ('guardado_en', models.DateTimeField(blank=True, db_column='guardado_en', null=True)),
                ('reenviado_en', models.DateTimeField(blank=True, db_column='reenviado_en', null=True)),
                ('recibido_en', models.DateTimeField(db_column='recibido_en')),
                ('payload_crudo', models.JSONField(db_column='payload_crudo')),
            ],
            options={
                'db_table': 'lecturas_suelo',
                'managed': False,
            },
        ),
    ]
